[package]
name = "LoadExc_client"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
dotenvy = "0.15"

# 升级至最新稳定 livekit 以避免老版本依赖冲突
livekit = "0.7.18"

# 可选 ROS2 依赖（仅在 --features ros2 时构建）
# 改为 crates.io 发布的 rclrs；暂不引入 sensor_msgs（避免无法解析的包导致构建失败）
rclrs = { version = "0.5", optional = true }

[features]
default = []
ros2 = ["dep:rclrs"]
